export const setupHTML = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signcert · 首次初始化</title>
<style>body{font:16px system-ui;max-width:860px;margin:40px auto;padding:0 20px;color:#172234;background:#f4f6fa}section{background:white;padding:24px;margin:20px 0;border-radius:12px}label{display:block;margin:14px 0}input,textarea,button{font:inherit;padding:10px;box-sizing:border-box}input,textarea{width:100%}button{cursor:pointer;margin:6px 8px 6px 0}button:disabled{cursor:default;opacity:.5}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#245cd5}small{display:block;color:#526176;margin-top:6px}[hidden]{display:none!important}.notice{border-left:4px solid #245cd5;padding-left:16px}input[type=checkbox]{width:auto}</style>
<h1>初始化你的证书系统</h1><p>在本页面创建根 CA、签发 CA、时间戳证书和 OCSP 证书。</p><p id="status" class="notice" role="status">正在检查初始化状态…</p>
<section id="create" hidden><h2>1. 创建证书</h2><form id="generate"><label>初始化主密钥<input id="master" type="password" minlength="64" maxlength="64" required autocomplete="off" spellcheck="false" placeholder="Cloudflare Secret：PKI_MASTER_KEY"></label><label>证书系统名称<input id="name" value="Signcert" maxlength="90" required></label><label>服务地址<input id="url" readonly></label>
<fieldset><legend>根证书有效期</legend><label>根证书生效时间（UTC）<input id="root-start" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label><label>根证书到期时间（UTC）<input id="root-end" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label></fieldset>
<fieldset><legend>签发 CA 有效期</legend><label>签发 CA 生效时间（UTC）<input id="issuer-start" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label><label>签发 CA 到期时间（UTC）<input id="issuer-end" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label></fieldset>
<small>以上时间均按 UTC 处理，北京时间需减 8 小时。签发 CA 有效期必须包含在根证书有效期内，两者均需覆盖当前时间。TSA/OCSP 默认从当前时间生效、有效 1 年，到期时间不超过签发 CA。</small>
<label>离线备份密码<input id="password" type="password" minlength="16" maxlength="1024" required autocomplete="new-password"></label><label>再次输入备份密码<input id="password-confirm" type="password" minlength="16" maxlength="1024" required autocomplete="new-password"></label><button id="generate-button" type="submit">生成证书与加密备份</button></form><small>密钥在当前浏览器生成。根私钥只写入加密备份；上传内容只包含服务证书、在线密钥和管理令牌。备份密码不会发送到服务器。</small></section>
<section id="backup" hidden><h2>2. 下载并保存</h2><p>保存加密备份及其密码。备份包含根私钥、在线密钥和管理令牌，服务器没有根私钥副本。</p><pre id="validity-preview"></pre><small>这里显示已生成或恢复的证书日期。修改上方日期后，需要重新生成证书与备份。</small><button id="download-backup">下载加密备份</button><button id="download-root">下载根证书 PEM</button><button id="download-chain">下载证书链 PEM</button><label><input id="saved" type="checkbox"> 我已保存备份文件和密码</label><h2>3. 完成初始化</h2><button id="commit" disabled>上传配置并启用服务</button><p id="commit-status" role="status"></p></section>
<section id="complete" hidden><h2 id="credentials-title">初始化完成</h2><p>使用管理令牌进入证书管理页面。令牌也保存在你下载的加密备份中。</p><label>管理令牌<textarea id="admin-token" rows="2" readonly spellcheck="false"></textarea></label><label>自定义时间戳令牌<textarea id="tsa-token" rows="2" readonly spellcheck="false"></textarea></label><p><a href="/admin">进入证书管理</a> · <a href="/ca/root.pem">下载根证书</a></p></section>
<section id="restore" hidden><h2>已有加密备份</h2><p>可在此解密自己的备份，提取根私钥或查看管理令牌。只有空系统才能使用该备份初始化；历史证书与撤销记录需从 D1 备份恢复。</p><form id="restore-form"><label>备份 JSON 文件<input id="backup-file" type="file" accept="application/json,.json" required></label><label>备份密码<input id="restore-password" type="password" minlength="16" maxlength="1024" required autocomplete="off"></label><button type="submit">在浏览器解密备份</button></form><p id="restore-status" role="status"></p><button id="download-private-root" hidden>下载根私钥 PEM（明文，请离线保管）</button></section>
<script src="/setup.js" defer></script></html>`;
