import {subjectEditor} from './subject-ui';
export const tsaHTML = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signcert · TSA 配置与签发</title>
<style>body{font:16px system-ui;max-width:900px;margin:40px auto;padding:0 20px;color:#172234;background:#f4f6fa}section{background:white;padding:24px;margin:20px 0;border-radius:12px}label{display:block;margin:14px 0}input,textarea,button{font:inherit;padding:10px;box-sizing:border-box}input,textarea{width:100%}button{cursor:pointer;margin:6px 8px 6px 0}button:disabled{opacity:.5;cursor:default}pre{white-space:pre-wrap;overflow-wrap:anywhere}small{display:block;color:#526176;margin-top:6px}a{color:#245cd5}[hidden]{display:none!important}</style>
<h1>TSA 配置与签发</h1><p><a href="/admin">返回证书管理</a></p>
<section><h2>管理认证</h2><label>管理令牌<input id="token" type="password" autocomplete="off" required placeholder="ADMIN_TOKEN"></label><button id="load" type="button">加载当前 TSA</button><p id="status" role="status">输入管理令牌，加载当前证书后配置重新签发。</p></section>
<section id="current" hidden><h2>当前 TSA 证书</h2><pre id="current-info"></pre><p><a href="/ca/tsa.cer" download>下载当前 TSA CER</a> · <a href="/ca/tsa.pem" download>下载当前 TSA PEM</a></p><pre id="issuer-info"></pre></section>
<section id="configuration" hidden><h2>重新签发并替换当前证书</h2><form id="issue"><fieldset id="fields"><label>证书名称（CN）<input id="name" maxlength="128" required></label>${subjectEditor('tsa-subject')}<label>TSA 生效时间（UTC）<input id="start" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label><label>TSA 到期时间（UTC）<input id="end" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" required></label><button id="issuer-dates" type="button">使用中间 CA 的完整有效期</button><button id="default-dates" type="button">使用当前时间起一年</button><small>北京时间需减 8 小时。有效期必须位于中间 CA 内，并覆盖当前时间。要验证历史时间戳，TSA 有效期还需覆盖所请求的历史时间。</small><p>签发后立即启用新证书和新私钥，覆盖当前服务配置。旧 TSA 证书、状态与时间戳记录保留；已生成的时间戳不会被重新签名。根 CA、中间 CA、访问令牌保持不变。</p><button id="issue-button" type="submit">重新签发并启用 TSA</button></fieldset></form><p id="result" role="status"></p><p>重新签发后，请备份 D1 数据库并保管 PKI_MASTER_KEY；初始化时下载的旧备份不包含本次新 TSA 私钥。</p></section>
<section id="confirmation" hidden><h2>确认重新签发</h2><pre id="preview"></pre><p>确认后立即替换当前 TSA 证书和私钥，旧证书记录保留。</p><button id="confirm-issue" type="button">确认签发并替换</button><button id="cancel-issue" type="button">取消，返回修改</button></section>
<script src="/tsa-admin.js" defer></script></html>`;
