export const adminHTML = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signcert 证书管理</title>
<style>body{font:16px system-ui;max-width:1000px;margin:40px auto;padding:0 20px;color:#172234;background:#f4f6fa}section{background:white;padding:24px;margin:20px 0;border-radius:12px}input,textarea,select,button{font:inherit;padding:8px;margin:6px 0;box-sizing:border-box}input,textarea{width:100%}button{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}code{overflow-wrap:anywhere}.scroll{overflow:auto}</style>
<h1>Signcert · 私有证书系统</h1><p>离线根 CA / 证书签发 / RFC 3161 时间戳 / OCSP / CRL</p>
<section><h2>管理认证</h2><label>管理令牌<input id="token" type="password" autocomplete="off" placeholder="ADMIN_TOKEN"></label><button id="load">加载证书</button><p>令牌仅保留在当前页面内存，刷新后需要重新输入。</p></section>
<section><h2>生成与签发证书</h2><form id="issue"><label>生成方式 <select id="issue-mode"><option value="browser">浏览器生成密钥，下载 CER / PFX</option><option value="csr">粘贴已有 CSR，仅签发证书</option></select></label><div id="browser-fields"><label>证书名称（CN）<input id="leaf-name" maxlength="128" required placeholder="My Application"></label><label>PFX 导出密码<input id="pfx-password" type="password" minlength="12" maxlength="1024" autocomplete="new-password" required></label><label>确认 PFX 密码<input id="pfx-confirm" type="password" minlength="12" maxlength="1024" autocomplete="new-password" required></label><p>浏览器生成 RSA-3072 私钥，只发送 CSR。PFX 包含私钥与完整证书链；密码不发送到服务器。请及时下载 PFX，刷新或再次生成会丢失当前页面中的私钥。若使用已有 CSR，私钥须由你另行保管。</p></div><div id="csr-fields" hidden><label>CSR（客户端生成密钥）<textarea id="csr" rows="8" placeholder="-----BEGIN CERTIFICATE REQUEST-----"></textarea></label></div><label>用途 <select id="profile"><option value="code-signing">代码签名</option><option value="server">TLS 服务端</option><option value="client">客户端认证</option></select></label> <label>有效天数 <input id="days" type="number" min="1" max="365" value="90" required></label>
<label><input id="custom-validity" type="checkbox" style="width:auto"> 自定义生效与到期时间</label><div id="custom-dates" hidden><label>证书生效时间（UTC）<input id="leaf-start" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59"></label><label>证书到期时间（UTC）<input id="leaf-end" type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59"></label><p>北京时间需减 8 小时。有效期必须位于签发 CA 内，并受最大有效天数限制。过去或未来的日期可能导致客户端拒绝使用证书。</p></div>
<label>TLS DNS 名称（逗号分隔，ASCII/IDNA）<input id="dns" placeholder="app.example.com"></label><button id="issue-button" type="submit">生成并签发</button></form><p id="issued-validity" role="status"></p><div id="downloads" hidden><button id="download-cer">下载 CER</button><button id="download-pem">下载 PEM</button><button id="download-pfx" hidden>下载 PFX</button><p>CER 仅含公钥证书，PFX 含私钥，请保管 PFX 文件和密码。</p></div><pre id="result" role="status"></pre></section>
<section id="renew-section" hidden><h2>服务证书续期</h2><p><a href="/admin/tsa">TSA 配置与重新签发（自定义有效期）</a></p><p>生成新密钥和证书并启用；旧证书及其状态记录保留。续期后请更新 D1 备份。</p><button id="renew-tsa">续期 TSA</button><button id="renew-ocsp">续期 OCSP</button><p id="renew-status" role="status"></p></section>
<section><h2>证书与撤销</h2><p><a href="/ca/root.cer" download>下载根证书 CER</a> · <a href="/ca/issuer.cer" download>下载签发 CA CER</a></p><p>撤销永久生效。OCSP 响应最多有效 5 分钟。服务证书撤销会停用相关服务。</p><div class="scroll"><table><thead><tr><th>名称 / 序列号</th><th>用途</th><th>状态</th><th>到期</th><th>操作</th></tr></thead><tbody id="rows"></tbody></table></div><button id="prev">上一页</button> <button id="next">下一页</button><p id="page"></p><p id="status" role="status"></p></section><section><h2>审计</h2><button id="audit">加载最近 200 条</button><pre id="audit-result"></pre></section><script src="/admin.js" defer></script></html>`;
